### ISSUE TITLE
Bug: Door detection defaults to "Closed" on machine start, regardless of physical door state

### ISSUE THREAD

**Issue by caerandir** [Snapmaker/Snapmaker2-Modules#21]
When the machine starts up, it assumes door state “closed” regardless of the actual door state. Only after closing the door properly once, the door state by e.g. M1010 reflects the physical door state.

This is a security problem when because of e.g. misaligned magnets (like after them falling off [again]) or a broken cable or connection the door sensor reports back “open” constantly. In this case the machine will never switch to “open” in its software, and if you then open the door mid-laser-job, it will not interrupt it, thus rendering the safty feature useless and putting your loved ones in danger.

If you want to verify this: Boot up your machine with at least one door open. Connect to the machine with Luban (either serial or network) and issue M1010. The answer will be Door State: Closed. Close all doors and open one again - M1010 will show Door state: open.

Expected behaviour: 
a) Always reflect the actual door state
b) As a default if e.g. cable is broken, machine should assume "open" for security reasons/to be fail safe

**Comment by Pastitas** [comment]
I think the reason for this might be that the first read that is done is by default returning true, or that the init value for the enclosure state variable is not set to false.

**Comment by scotthsl** [comment]
Hi all,
the bug has been fixed, please update the lastest module firmware.
